title: Kurt Cobain a Nirvana
baseURL: https://candycanelane94.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Život Kurta Cobaina a cesta kapely Nirvana
  authors: Jan Lahoda, Linda Miklová, Marek Štvrtňa

